<?php
declare(strict_types=1);
namespace App\Application\Services;
use App\Domain\Services\PricingEngine; use App\Infrastructure\Database\DB; use App\Shared\Exceptions\ApiException; use App\Shared\Support\PersianText;
final class CatalogService {
 public function __construct(private PricingEngine $pricing){}
 public function products(array $q): array { $page=max(1,(int)($q['page']??1));$size=min(60,max(1,(int)($q['pageSize']??24)));$term=PersianText::normalize((string)($q['q']??''));$where="p.status='published'";$params=[];if($term!==''){$where.=' AND p.search_text ILIKE :q';$params[':q']='%'.$term.'%';}$params[':limit']=$size;$params[':offset']=($page-1)*$size;$rows=DB::fetchAll("SELECT p.public_id id,p.slug,p.title,p.subtitle,s.public_id sku_id,s.minimum_order_quantity,s.reference_unit_price,s.status availability,s.fast_dispatch FROM products p LEFT JOIN LATERAL(SELECT * FROM skus WHERE product_id=p.id AND status<>'archived' ORDER BY id LIMIT 1)s ON true WHERE $where ORDER BY p.created_at DESC LIMIT :limit OFFSET :offset",$params);$count=DB::fetch("SELECT count(*) c FROM products p WHERE $where",array_diff_key($params,[':limit'=>1,':offset'=>1]));return ['items'=>$rows,'page'=>$page,'pageSize'=>$size,'total'=>(int)$count['c']]; }
 public function product(string $slug): array { $p=DB::fetch("SELECT p.*,pub.name publisher_name,se.name series_name FROM products p LEFT JOIN publishers pub ON pub.id=p.publisher_id LEFT JOIN series se ON se.id=p.series_id WHERE p.slug=:s AND p.status='published'",[':s'=>$slug]);if(!$p)throw new ApiException('PRODUCT_NOT_FOUND','محصول یافت نشد.',404);$p['skus']=DB::fetchAll('SELECT public_id id,code,isbn,attributes,minimum_order_quantity,reference_unit_price,fast_dispatch,status,pricing_version FROM skus WHERE product_id=:id',[':id'=>$p['id']]);unset($p['id']);return $p; }
 public function quote(string $skuId,int $quantity): array { $sku=DB::fetch('SELECT * FROM skus WHERE public_id=:id',[':id'=>$skuId]);if(!$sku)throw new ApiException('SKU_NOT_FOUND','SKU یافت نشد.',404);$tiers=DB::fetchAll('SELECT * FROM pricing_tiers WHERE sku_id=:id AND effective_from<=now() AND (effective_to IS NULL OR effective_to>now()) ORDER BY min_quantity',[':id'=>$sku['id']]);$stock=DB::fetch('SELECT COALESCE(sum(on_hand-reserved-safety_stock),0) available FROM inventory_balances WHERE sku_id=:id',[':id'=>$sku['id']]);return $this->pricing->quote($sku,$tiers,$quantity,(int)$stock['available']); }
 public function taxonomy(string $table): array { if(!in_array($table,['series','publishers','categories'],true))return[];return DB::fetchAll("SELECT public_id id,slug,name FROM $table ORDER BY name"); }
}
