<?php
declare(strict_types=1);
namespace App\Application\Services;
use App\Infrastructure\Database\DB; use App\Shared\Exceptions\ApiException; use App\Shared\Support\Id; use PDO;
final class AccountService {
 public function me(int $u):array{$r=DB::fetch('SELECT public_id id,phone,name,customer_type AS "customerType" FROM users WHERE id=:u',[':u'=>$u]);if(!$r)throw new ApiException('AUTH_SESSION_REVOKED','کاربر یافت نشد.',401);return $r;}
 public function update(int $u,array $d):array{$types=['individual','teacher','language_school','bookstore','school','other_business'];if(isset($d['customerType'])&&!in_array($d['customerType'],$types,true))throw new ApiException('VALIDATION_FAILED','نوع مشتری معتبر نیست.',422,['customerType'=>'نامعتبر است.']);DB::execute('UPDATE users SET name=COALESCE(:name,name),customer_type=COALESCE(:type,customer_type) WHERE id=:u',[':name'=>isset($d['name'])?trim((string)$d['name']):null,':type'=>$d['customerType']??null,':u'=>$u]);return $this->me($u);}
 public function business(int $u):?array{$r=DB::fetch('SELECT data,version FROM business_profiles WHERE user_id=:u',[':u'=>$u]);return !$r?null:['version'=>(int)$r['version']]+(json_decode($r['data'],true)?:[]);}
 public function saveBusiness(int $u,array $d):array{DB::transaction(function(PDO $p)use($u,$d):void{$row=$p->prepare('SELECT version FROM business_profiles WHERE user_id=:u FOR UPDATE');$row->execute([':u'=>$u]);$cur=$row->fetch();if($cur&&isset($d['version'])&&(int)$d['version']!==(int)$cur['version'])throw new ApiException('RESOURCE_VERSION_CONFLICT','نسخه پروفایل تغییر کرده است.',409);unset($d['version']);$json=json_encode($d,JSON_UNESCAPED_UNICODE);if($cur)$p->prepare('UPDATE business_profiles SET data=CAST(:d AS jsonb),version=version+1,updated_at=now() WHERE user_id=:u')->execute([':d'=>$json,':u'=>$u]);else $p->prepare('INSERT INTO business_profiles(user_id,data)VALUES(:u,CAST(:d AS jsonb))')->execute([':u'=>$u,':d'=>$json]);});return $this->business($u)??[];}
 public function delete(int $u):void{DB::transaction(function(PDO $p)use($u):void{$p->prepare("UPDATE users SET status='pending_deletion' WHERE id=:u")->execute([':u'=>$u]);$p->prepare('UPDATE sessions SET revoked_at=now() WHERE user_id=:u AND revoked_at IS NULL')->execute([':u'=>$u]);});}
 public function addresses(int $u):array{$r=DB::fetchAll('SELECT public_id,version,is_default,data FROM addresses WHERE user_id=:u AND deleted_at IS NULL ORDER BY is_default DESC,id DESC',[':u'=>$u]);return array_map(static fn($x)=>['id'=>$x['public_id'],'version'=>(int)$x['version'],'isDefault'=>(bool)$x['is_default']]+(json_decode($x['data'],true)?:[]),$r);}
 public function addAddress(int $u,array $d):array{$this->validateAddress($d);$id=Id::make('adr');DB::transaction(function(PDO $p)use($u,$d,$id):void{$countStmt=$p->prepare('SELECT count(*) FROM addresses WHERE user_id=:u AND deleted_at IS NULL');$countStmt->execute([':u'=>$u]);$count=(int)$countStmt->fetchColumn();$default=!empty($d['isDefault'])||$count===0;if($default)$p->prepare('UPDATE addresses SET is_default=false WHERE user_id=:u AND deleted_at IS NULL')->execute([':u'=>$u]);$p->prepare('INSERT INTO addresses(public_id,user_id,data,is_default)VALUES(:id,:u,CAST(:d AS jsonb),:default)')->execute([':id'=>$id,':u'=>$u,':d'=>json_encode($d,JSON_UNESCAPED_UNICODE),':default'=>$default]);});return $this->address($u,$id);}
 public function updateAddress(int $u,string $id,array $d):array{DB::transaction(function(PDO $p)use($u,$id,$d):void{$s=$p->prepare('SELECT * FROM addresses WHERE public_id=:id AND user_id=:u AND deleted_at IS NULL FOR UPDATE');$s->execute([':id'=>$id,':u'=>$u]);$r=$s->fetch();if(!$r)throw new ApiException('RESOURCE_VERSION_CONFLICT','نشانی یافت نشد.',404);if((int)($d['version']??0)!==(int)$r['version'])throw new ApiException('RESOURCE_VERSION_CONFLICT','نسخه نشانی تغییر کرده است.',409);$old=json_decode($r['data'],true)?:[];unset($d['version']);$new=array_merge($old,$d);$this->validateAddress($new);$p->prepare('UPDATE addresses SET data=CAST(:d AS jsonb),version=version+1 WHERE id=:pk')->execute([':d'=>json_encode($new,JSON_UNESCAPED_UNICODE),':pk'=>$r['id']]);});return $this->address($u,$id);}
 public function removeAddress(int $u,string $id,int $version):void{DB::transaction(function(PDO $p)use($u,$id,$version):void{$s=$p->prepare('UPDATE addresses SET deleted_at=now(),is_default=false,version=version+1 WHERE public_id=:id AND user_id=:u AND deleted_at IS NULL AND version=:v');$s->execute([':id'=>$id,':u'=>$u,':v'=>$version]);if($s->rowCount()!==1)throw new ApiException('RESOURCE_VERSION_CONFLICT','نشانی یافت نشد یا نسخه تغییر کرده است.',409);});}
 public function makeDefault(int $u,string $id,int $version):array{DB::transaction(function(PDO $p)use($u,$id,$version):void{$s=$p->prepare('SELECT * FROM addresses WHERE public_id=:id AND user_id=:u AND deleted_at IS NULL FOR UPDATE');$s->execute([':id'=>$id,':u'=>$u]);$r=$s->fetch();if(!$r||(int)$r['version']!==$version)throw new ApiException('RESOURCE_VERSION_CONFLICT','نسخه نشانی تغییر کرده است.',409);$p->prepare('UPDATE addresses SET is_default=false WHERE user_id=:u AND deleted_at IS NULL')->execute([':u'=>$u]);$p->prepare('UPDATE addresses SET is_default=true,version=version+1 WHERE id=:id')->execute([':id'=>$r['id']]);});return $this->address($u,$id);}
 private function address(int $u,string $id):array{$r=DB::fetch('SELECT public_id,version,is_default,data FROM addresses WHERE public_id=:id AND user_id=:u AND deleted_at IS NULL',[':id'=>$id,':u'=>$u]);if(!$r)throw new ApiException('RESOURCE_VERSION_CONFLICT','نشانی یافت نشد.',404);return ['id'=>$r['public_id'],'version'=>(int)$r['version'],'isDefault'=>(bool)$r['is_default']]+(json_decode($r['data'],true)?:[]);}
 private function validateAddress(array $d):void{foreach(['recipientName','recipientPhone','provinceId','cityId','postalCode','addressLine'] as $f)if(empty($d[$f]))throw new ApiException('VALIDATION_FAILED','اطلاعات نشانی ناقص است.',422,[$f=>'الزامی است.']);}
}
