<?php
declare(strict_types=1);
namespace App\Application\Services;
use App\Infrastructure\Database\DB; use App\Shared\Exceptions\ApiException; use App\Shared\Support\Id; use PDO;
final class AdminConfigurationService {
 public function __construct(private AuditService $audit){}
 public function coupons():array{return DB::fetchAll('SELECT public_id id,code,type,value,rules,expires_at AS "expiresAt",active FROM coupons ORDER BY id DESC LIMIT 100');}
 public function createCoupon(int $actor,array $d):array{return DB::transaction(function(PDO $p)use($actor,$d):array{$code=strtoupper(trim((string)($d['code']??'')));$type=(string)($d['type']??'');$value=(int)($d['value']??0);if($code===''||!in_array($type,['fixed','percent','percentage'],true)||$value<1)throw new ApiException('VALIDATION_FAILED','مشخصات کوپن معتبر نیست.',422);$id=Id::make('cpn');try{$p->prepare('INSERT INTO coupons(public_id,code,type,value,rules,expires_at,active)VALUES(:id,:code,:type,:value,CAST(:rules AS jsonb),:expires,:active)')->execute([':id'=>$id,':code'=>$code,':type'=>$type,':value'=>$value,':rules'=>json_encode($d['rules']??[]),':expires'=>$d['expiresAt']??null,':active'=>$d['active']??true]);}catch(\PDOException){throw new ApiException('RESOURCE_CONFLICT','کد کوپن تکراری است.',409);}$this->audit->record($p,$actor,'coupon.create','coupon',$id,null,['code'=>$code]);return ['id'=>$id,'code'=>$code];});}
 public function updateCoupon(int $actor,string $id,array $d):array{return DB::transaction(function(PDO $p)use($actor,$id,$d):array{$s=$p->prepare('SELECT * FROM coupons WHERE public_id=:id FOR UPDATE');$s->execute([':id'=>$id]);$c=$s->fetch();if(!$c)throw new ApiException('COUPON_NOT_FOUND','کوپن یافت نشد.',404);$active=array_key_exists('active',$d)?(bool)$d['active']:(bool)$c['active'];$rules=array_key_exists('rules',$d)?$d['rules']:json_decode($c['rules'],true);$p->prepare('UPDATE coupons SET active=:active,rules=CAST(:rules AS jsonb),expires_at=:expires WHERE id=:pk')->execute([':active'=>$active,':rules'=>json_encode($rules?:[]),':expires'=>$d['expiresAt']??$c['expires_at'],':pk'=>$c['id']]);$this->audit->record($p,$actor,'coupon.update','coupon',$id,['active'=>$c['active']],['active'=>$active]);return ['id'=>$id,'active'=>$active];});}
 public function setting(string $key):array{$v=DB::fetch('SELECT value FROM settings WHERE key=:key',[':key'=>$key]);return ['key'=>$key,'value'=>$v?self::json($v['value']):[]];}
 public function saveSetting(int $actor,string $key,array $value):array{if(!in_array($key,['commerce','support','shipping'],true))throw new ApiException('SETTING_NOT_FOUND','تنظیمات یافت نشد.',404);return DB::transaction(function(PDO $p)use($actor,$key,$value):array{$before=$p->prepare('SELECT value FROM settings WHERE key=:key FOR UPDATE');$before->execute([':key'=>$key]);$old=$before->fetchColumn();$p->prepare('INSERT INTO settings(key,value)VALUES(:key,CAST(:value AS jsonb)) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value')->execute([':key'=>$key,':value'=>json_encode($value)]);$this->audit->record($p,$actor,'settings.update','setting',$key,$old?self::json($old):null,$value);return ['key'=>$key,'value'=>$value];});}
 private static function json(mixed $v):array{$d=is_array($v)?$v:json_decode((string)$v,true);return is_array($d)?$d:[];}
}
