<?php

declare(strict_types=1);

namespace App\Application\Services;

use App\Infrastructure\Database\DB;
use App\Shared\Exceptions\ApiException;
use App\Shared\Support\Id;
use PDO;

final class AdminCatalogService
{
    public function __construct(private AuditService $audit) {}
    public function products(): array { return DB::fetchAll('SELECT public_id id,slug,title,status,created_at AS "createdAt" FROM products ORDER BY id DESC LIMIT 100'); }
    public function createProduct(int $actor,array $data): array { return DB::transaction(function(PDO $pdo)use($actor,$data):array{$title=trim((string)($data['title']??''));$slug=trim((string)($data['slug']??''));if($title===''||$slug==='')throw new ApiException('VALIDATION_FAILED','عنوان و slug الزامی هستند.',422);$id=Id::make('prd');$s=$pdo->prepare("INSERT INTO products(public_id,slug,title,subtitle,description,status,search_text) VALUES(:id,:slug,:title,:subtitle,:description,'draft',:search)");try{$s->execute([':id'=>$id,':slug'=>$slug,':title'=>$title,':subtitle'=>$data['subtitle']??null,':description'=>$data['description']??null,':search'=>$title.' '.($data['subtitle']??'')]);}catch(\PDOException $e){throw new ApiException('RESOURCE_CONFLICT','Slug تکراری است.',409);} $this->audit->record($pdo,$actor,'catalog.product.create','product',$id,null,['title'=>$title,'slug'=>$slug]);return ['id'=>$id,'status'=>'draft'];}); }
    public function updateProduct(int $actor,string $id,array $data):array{return DB::transaction(function(PDO $pdo)use($actor,$id,$data):array{$s=$pdo->prepare('SELECT * FROM products WHERE public_id=:id FOR UPDATE');$s->execute([':id'=>$id]);$p=$s->fetch();if(!$p)throw new ApiException('PRODUCT_NOT_FOUND','محصول یافت نشد.',404);$title=array_key_exists('title',$data)?trim((string)$data['title']):$p['title'];$subtitle=array_key_exists('subtitle',$data)?$data['subtitle']:$p['subtitle'];$description=array_key_exists('description',$data)?$data['description']:$p['description'];$pdo->prepare('UPDATE products SET title=:title,subtitle=:subtitle,description=:description,search_text=:search WHERE id=:pk')->execute([':title'=>$title,':subtitle'=>$subtitle,':description'=>$description,':search'=>$title.' '.($subtitle??''),':pk'=>$p['id']]);$this->audit->record($pdo,$actor,'catalog.product.update','product',$id,['title'=>$p['title']],['title'=>$title]);return ['id'=>$id,'title'=>$title];});}
    public function productStatus(int $actor,string $id,string $status):array{if(!in_array($status,['published','archived'],true))throw new ApiException('VALIDATION_FAILED','وضعیت محصول معتبر نیست.',422);return DB::transaction(function(PDO $pdo)use($actor,$id,$status):array{$s=$pdo->prepare('SELECT status FROM products WHERE public_id=:id FOR UPDATE');$s->execute([':id'=>$id]);$old=$s->fetchColumn();if($old===false)throw new ApiException('PRODUCT_NOT_FOUND','محصول یافت نشد.',404);$pdo->prepare('UPDATE products SET status=:status WHERE public_id=:id')->execute([':status'=>$status,':id'=>$id]);$this->audit->record($pdo,$actor,'catalog.product.'.$status,'product',$id,['status'=>$old],['status'=>$status]);return ['id'=>$id,'status'=>$status];});}
    public function tiers(string $skuId):array{$sku=DB::fetch('SELECT public_id,minimum_order_quantity AS "minimumOrderQuantity",pricing_version AS "pricingVersion" FROM skus WHERE public_id=:id',[':id'=>$skuId]);if(!$sku)throw new ApiException('SKU_NOT_FOUND','SKU یافت نشد.',404);$sku['tiers']=DB::fetchAll('SELECT min_quantity AS "minQuantity",max_quantity AS "maxQuantity",unit_price AS "unitPrice",effective_from AS "effectiveFrom",effective_to AS "effectiveTo" FROM pricing_tiers WHERE sku_id=(SELECT id FROM skus WHERE public_id=:id) ORDER BY min_quantity',[':id'=>$skuId]);return $sku;}
    public function saveTiers(int $actor,string $skuId,array $data):array{return DB::transaction(function(PDO $pdo)use($actor,$skuId,$data):array{$s=$pdo->prepare('SELECT * FROM skus WHERE public_id=:id FOR UPDATE');$s->execute([':id'=>$skuId]);$sku=$s->fetch();if(!$sku)throw new ApiException('SKU_NOT_FOUND','SKU یافت نشد.',404);$tiers=$data['tiers']??[];$minimum=(int)($data['minimumOrderQuantity']??$sku['minimum_order_quantity']);$this->assertTiers($tiers,$minimum);$pdo->prepare('DELETE FROM pricing_tiers WHERE sku_id=:sku')->execute([':sku'=>$sku['id']]);$insert=$pdo->prepare('INSERT INTO pricing_tiers(sku_id,min_quantity,max_quantity,unit_price,effective_from,effective_to)VALUES(:sku,:min,:max,:price,:from,:to)');foreach($tiers as $tier)$insert->execute([':sku'=>$sku['id'],':min'=>(int)$tier['minQuantity'],':max'=>$tier['maxQuantity']??null,':price'=>(int)$tier['unitPrice'],':from'=>$data['effectiveFrom']??gmdate('c'),':to'=>$data['effectiveTo']??null]);$pdo->prepare('UPDATE skus SET minimum_order_quantity=:min,pricing_version=pricing_version+1 WHERE id=:id')->execute([':min'=>$minimum,':id'=>$sku['id']]);$this->audit->record($pdo,$actor,'catalog.pricing.update','sku',$skuId,null,['tiers'=>$tiers]);return ['skuId'=>$skuId,'minimumOrderQuantity'=>$minimum,'tiers'=>$tiers];});}
    public function adjustInventory(int $actor,array $data):array{return DB::transaction(function(PDO $pdo)use($actor,$data):array{$qty=(int)($data['quantity']??0);$reason=trim((string)($data['reason']??''));if($qty===0||$reason==='')throw new ApiException('VALIDATION_FAILED','مقدار غیرصفر و دلیل الزامی است.',422);$s=$pdo->prepare('SELECT s.id sku_id,w.id warehouse_id FROM skus s JOIN warehouses w ON w.public_id=:warehouse WHERE s.public_id=:sku FOR UPDATE');$s->execute([':sku'=>$data['skuId']??'',':warehouse'=>$data['warehouseId']??'']);$row=$s->fetch();if(!$row)throw new ApiException('INVENTORY_RESOURCE_NOT_FOUND','SKU یا انبار یافت نشد.',404);$pdo->prepare('UPDATE inventory_balances SET on_hand=on_hand+:quantity,version=version+1 WHERE sku_id=:sku AND warehouse_id=:warehouse')->execute([':quantity'=>$qty,':sku'=>$row['sku_id'],':warehouse'=>$row['warehouse_id']]);$id=Id::make('imv');$pdo->prepare('INSERT INTO inventory_movements(public_id,sku_id,warehouse_id,quantity,reason,actor_id)VALUES(:id,:sku,:warehouse,:quantity,:reason,:actor)')->execute([':id'=>$id,':sku'=>$row['sku_id'],':warehouse'=>$row['warehouse_id'],':quantity'=>$qty,':reason'=>$reason,':actor'=>$actor]);$this->audit->record($pdo,$actor,'inventory.adjust','sku',(string)($data['skuId']??''),null,['quantity'=>$qty,'reason'=>$reason]);return ['id'=>$id];});}
    private function assertTiers(array $tiers,int $minimum):void{if($tiers===[])throw new ApiException('VALIDATION_FAILED','حداقل یک tier الزامی است.',422);$previous=null;foreach($tiers as $i=>$tier){$min=(int)($tier['minQuantity']??0);$max=array_key_exists('maxQuantity',$tier)&&$tier['maxQuantity']!==null?(int)$tier['maxQuantity']:null;$price=(int)($tier['unitPrice']??0);if($min<1||$price<1||($max!==null&&$max<$min)||($previous!==null&&$min!==$previous+1)||($i===0&&$min!==$minimum))throw new ApiException('INVALID_PRICING_TIERS','Tierها باید مرتب، پیوسته و بدون هم‌پوشانی باشند.',422);$previous=$max;if($max===null&&$i!==array_key_last($tiers))throw new ApiException('INVALID_PRICING_TIERS','Tier بدون سقف باید آخرین باشد.',422);}}
}
