<?php
declare(strict_types=1);
namespace App\Application\Services;
use App\Infrastructure\Database\DB; use App\Shared\Exceptions\ApiException; use App\Shared\Support\Id; use Firebase\JWT\JWT; use PDO;
final class AuthService {
 public function request(string $phone): array { $phone=$this->phone($phone);$recent=DB::fetch("SELECT count(*) c FROM otp_challenges WHERE phone=:p AND expires_at>now()-interval '10 minutes'",[':p'=>$phone]);if((int)$recent['c']>=3)throw new ApiException('OTP_RATE_LIMITED','تعداد درخواست بیش از حد مجاز است.',429);$id=Id::make('otp');$code=(string)random_int(100000,999999);DB::execute("INSERT INTO otp_challenges(public_id,phone,code_hash,expires_at) VALUES(:id,:p,:h,now()+interval '2 minutes')",[':id'=>$id,':p'=>$phone,':h'=>password_hash($code,PASSWORD_DEFAULT)]);$out=['challengeId'=>$id,'expiresInSeconds'=>120,'resendAfterSeconds'=>60,'maskedPhone'=>substr($phone,0,4).'•••'.substr($phone,-4)];if(($_ENV['APP_ENV']??'development')!=='production')$out['developmentCode']=$code;return $out; }
 public function verify(string $challenge,string $code): array { return DB::transaction(function(PDO $pdo)use($challenge,$code){$s=$pdo->prepare('SELECT * FROM otp_challenges WHERE public_id=:id FOR UPDATE');$s->execute([':id'=>$challenge]);$otp=$s->fetch();if(!$otp||$otp['consumed_at']||strtotime($otp['expires_at'])<time())throw new ApiException('OTP_EXPIRED','کد منقضی شده است.',422);if((int)$otp['attempts']>=5)throw new ApiException('OTP_MAX_ATTEMPTS_REACHED','تعداد تلاش بیش از حد است.',429);if(!password_verify($code,$otp['code_hash'])){$pdo->prepare('UPDATE otp_challenges SET attempts=attempts+1 WHERE id=:id')->execute([':id'=>$otp['id']]);throw new ApiException('OTP_INVALID','کد صحیح نیست.',422);}$pdo->prepare('UPDATE otp_challenges SET consumed_at=now() WHERE id=:id')->execute([':id'=>$otp['id']]);$s=$pdo->prepare('SELECT * FROM users WHERE phone=:p');$s->execute([':p'=>$otp['phone']]);$user=$s->fetch();$new=false;if(!$user){$new=true;$uid=Id::make('usr');$s=$pdo->prepare('INSERT INTO users(public_id,phone)VALUES(:id,:p) RETURNING *');$s->execute([':id'=>$uid,':p'=>$otp['phone']]);$user=$s->fetch();}$refresh=bin2hex(random_bytes(32));$sid=Id::make('ses');$pdo->prepare("INSERT INTO sessions(public_id,user_id,refresh_hash,expires_at)VALUES(:s,:u,:h,now()+interval '30 days')")->execute([':s'=>$sid,':u'=>$user['id'],':h'=>hash('sha256',$refresh)]);return ['accessToken'=>$this->jwt((int)$user['id'],$user['public_id']),'refreshToken'=>$refresh,'expiresIn'=>900,'user'=>['id'=>$user['public_id'],'phone'=>$user['phone'],'name'=>$user['name']],'isNewUser'=>$new,'profileCompleted'=>!empty($user['name'])];}); }
 public function refresh(string $token): array { $hash=hash('sha256',$token);return DB::transaction(function(PDO $pdo)use($hash){$s=$pdo->prepare('SELECT s.*,u.public_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE refresh_hash=:h FOR UPDATE');$s->execute([':h'=>$hash]);$row=$s->fetch();if(!$row||$row['revoked_at']||strtotime($row['expires_at'])<time())throw new ApiException('AUTH_SESSION_REVOKED','نشست معتبر نیست.',401);$new=bin2hex(random_bytes(32));$pdo->prepare('UPDATE sessions SET refresh_hash=:h WHERE id=:id')->execute([':h'=>hash('sha256',$new),':id'=>$row['id']]);return ['accessToken'=>$this->jwt((int)$row['user_id'],$row['public_id']),'refreshToken'=>$new,'expiresIn'=>900];}); }
 private function jwt(int $id,string $public): string { $now=time();return JWT::encode(['iss'=>'pardis-api','sub'=>$id,'uid'=>$public,'iat'=>$now,'exp'=>$now+(int)($_ENV['JWT_TTL']??900)],(string)$_ENV['JWT_SECRET'],(string)($_ENV['JWT_ALGO']??'HS256')); }
 private function phone(string $v): string { $v=preg_replace('/\D+/','',$v);if(str_starts_with($v,'09'))$v='98'.substr($v,1);if(!preg_match('/^989\d{9}$/',$v))throw new ApiException('VALIDATION_FAILED','شماره موبایل معتبر نیست.',422,['phone'=>'فرمت شماره صحیح نیست.']);return '+'.$v; }
}
