<?php
declare(strict_types=1);
namespace App\Application\Services;
use App\Infrastructure\Database\DB; use App\Shared\Exceptions\ApiException; use App\Shared\Support\Id; use PDO;
final class CartService {
 public function __construct(private CatalogService $catalog){}
 public function create(): array {$token=Id::make('gct');$id=Id::make('cart');DB::execute('INSERT INTO carts(public_id,guest_token_hash)VALUES(:i,:t)',[':i'=>$id,':t'=>hash('sha256',$token)]);return ['cartId'=>$id,'guestCartToken'=>$token,'version'=>1];}
 public function get(?int $user,string $token): array {$cart=$this->find($user,$token);return $this->shape($cart);}
 public function add(?int $user,string $token,string $sku,int $qty): array {$cart=$this->find($user,$token);$quote=$this->catalog->quote($sku,$qty);$s=DB::fetch('SELECT id FROM skus WHERE public_id=:id',[':id'=>$sku]);DB::execute('INSERT INTO cart_items(public_id,cart_id,sku_id,quantity)VALUES(:p,:c,:s,:q) ON CONFLICT(cart_id,sku_id) DO UPDATE SET quantity=EXCLUDED.quantity',[':p'=>Id::make('ci'),':c'=>$cart['id'],':s'=>$s['id'],':q'=>$qty]);DB::execute('UPDATE carts SET version=version+1 WHERE id=:id',[':id'=>$cart['id']]);return $this->get($user,$token);}
 private function find(?int $user,string $token): array {$row=$user?DB::fetch("SELECT * FROM carts WHERE user_id=:u AND status='active'",[':u'=>$user]):DB::fetch("SELECT * FROM carts WHERE guest_token_hash=:t AND status='active'",[':t'=>hash('sha256',$token)]);if(!$row&&$user){DB::execute('INSERT INTO carts(public_id,user_id)VALUES(:p,:u)',[':p'=>Id::make('cart'),':u'=>$user]);$row=DB::fetch("SELECT * FROM carts WHERE user_id=:u AND status='active'",[':u'=>$user]);}if(!$row)throw new ApiException('CART_NOT_FOUND','سبد یافت نشد.',404);return $row;}
 private function shape(array $cart): array {$items=DB::fetchAll('SELECT ci.public_id id,ci.quantity,s.public_id sku_id,p.title FROM cart_items ci JOIN skus s ON s.id=ci.sku_id JOIN products p ON p.id=s.product_id WHERE ci.cart_id=:c',[':c'=>$cart['id']]);$out=[];$sum=0;$saving=0;foreach($items as $i){try{$q=$this->catalog->quote($i['sku_id'],(int)$i['quantity']);$sum+=$q['lineSubtotal'];$saving+=$q['lineSaving'];$out[]=array_merge($i,$q,['warnings'=>[]]);}catch(ApiException $e){$out[]=array_merge($i,['warnings'=>[$e->errorCode]]);}}return ['id'=>$cart['public_id'],'version'=>(int)$cart['version'],'currency'=>'TOMAN','items'=>$out,'summary'=>['lineCount'=>count($out),'totalQuantity'=>array_sum(array_column($out,'quantity')),'merchandiseSubtotal'=>$sum,'wholesaleSaving'=>$saving,'couponDiscount'=>0,'shipping'=>null,'payable'=>$sum],'isValidForCheckout'=>count($out)>0&&!array_filter($out,fn($x)=>!empty($x['warnings'])),'warnings'=>[]];}
}
