<?php
declare(strict_types=1);
use App\Http\Routers\Router;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\AdminOperationsController;
use App\Http\Controllers\AdminCatalogController;
use App\Http\Controllers\AdminConfigurationController;
use App\Http\Controllers\AdminBestSellingController;
use App\Http\Controllers\ReportController;

return static function (Router $r): void {
    $r->get('v1', '/health/live', SystemController::class, 'live');
    $r->get('v1', '/health/ready', SystemController::class, 'ready');
    $r->get('v1', '/bootstrap', SystemController::class, 'bootstrap');
    $r->get('v1', '/home', SystemController::class, 'home');
    $r->get('v1', '/navigation', SystemController::class, 'navigation');
    $r->post('v1', '/auth/otp/request', AuthController::class, 'requestOtp');
    $r->post('v1', '/auth/otp/verify', AuthController::class, 'verifyOtp');
    $r->post('v1', '/auth/token/refresh', AuthController::class, 'refresh');
    $r->post('v1', '/auth/logout', AuthController::class, 'logout', 'auth');
    $r->post('v1', '/auth/logout-all', AuthController::class, 'logoutAll', 'auth');
    $r->get('v1', '/auth/sessions', AuthController::class, 'sessions', 'auth');
    $r->delete('v1', '/auth/sessions/{sessionId}', AuthController::class, 'revokeSession', 'auth');
    $r->get('v1', '/products', CatalogController::class, 'products');
    $r->get('v1', '/products/best-selling', CatalogController::class, 'bestSelling');
    $r->get('v1', '/products/best-selling/search', CatalogController::class, 'searchBestSelling');
    $r->get('v1', '/products/fast-dispatch', CatalogController::class, 'fastDispatch');
    $r->get('v1', '/products/{productSlug}', CatalogController::class, 'product');
    $r->get('v1', '/products/{productSlug}/related', CatalogController::class, 'related');
    $r->get('v1', '/series', CatalogController::class, 'series');
    $r->get('v1', '/series/featured', CatalogController::class, 'featuredSeries');
    $r->get('v1', '/series/{seriesSlug}', CatalogController::class, 'seriesDetail');
    $r->get('v1', '/search/suggestions', CatalogController::class, 'searchSuggestions');
    $r->get('v1', '/search', CatalogController::class, 'search');
    $r->get('v1', '/publishers', CatalogController::class, 'publishers');
    $r->get('v1', '/categories', CatalogController::class, 'categories');
    $r->get('v1', '/catalog/facets', CatalogController::class, 'facets');
    $r->get('v1', '/content/pages/{slug}', ContentController::class, 'page');
    $r->get('v1', '/skus/{skuId}/pricing', CatalogController::class, 'pricing');
    $r->post('v1', '/pricing/quote-line', CatalogController::class, 'quote');
    $r->post('v1', '/availability/check', CatalogController::class, 'availability');
    $r->post('v1', '/carts', CartController::class, 'create');
    $r->get('v1', '/cart', CartController::class, 'show');
    $r->post('v1', '/cart/items', CartController::class, 'add');
    $r->patch('v1', '/cart/items/{itemId}', CartController::class, 'update');
    $r->delete('v1', '/cart/items/{itemId}', CartController::class, 'remove');
    $r->delete('v1', '/cart/items', CartController::class, 'clear');
    $r->post('v1', '/cart/validate', CartController::class, 'validate');
    $r->post('v1', '/cart/merge', CartController::class, 'merge', 'auth');
    $r->post('v1', '/cart/coupon', CartController::class, 'applyCoupon');
    $r->delete('v1', '/cart/coupon', CartController::class, 'removeCoupon');
    $r->post('v1', '/checkout/quote', CheckoutController::class, 'quote', 'auth');
    $r->post('v1', '/orders', CheckoutController::class, 'order', 'auth');
    $r->post('v1', '/payments/attempts', CheckoutController::class, 'payment', 'auth');
    $r->get('v1', '/payments/attempts/{attemptId}', CheckoutController::class, 'paymentAttempt', 'auth');
    $r->post('v1', '/payments/attempts/{attemptId}/verify', CheckoutController::class, 'verify', 'auth');
    $r->get('v1', '/orders/{orderId}/payment', CheckoutController::class, 'orderPayment', 'auth');
    $r->get('v1', '/payments/callback/{provider}', CheckoutController::class, 'callback');
    $r->post('v1', '/payments/callback/{provider}', CheckoutController::class, 'callback');
    $r->post('v1', '/webhooks/payments/{provider}', CheckoutController::class, 'webhook');
    $r->get('v1', '/me', AccountController::class, 'me', 'auth');
    $r->patch('v1', '/me', AccountController::class, 'update', 'auth');
    $r->get('v1', '/me/business-profile', AccountController::class, 'business', 'auth');
    $r->put('v1', '/me/business-profile', AccountController::class, 'saveBusiness', 'auth');
    $r->delete('v1', '/me', AccountController::class, 'deleteAccount', 'auth');
    $r->get('v1', '/me/addresses', AccountController::class, 'addresses', 'auth');
    $r->post('v1', '/me/addresses', AccountController::class, 'addAddress', 'auth');
    $r->patch('v1', '/me/addresses/{addressId}', AccountController::class, 'updateAddress', 'auth');
    $r->delete('v1', '/me/addresses/{addressId}', AccountController::class, 'removeAddress', 'auth');
    $r->post('v1', '/me/addresses/{addressId}/default', AccountController::class, 'defaultAddress', 'auth');
    $r->get('v1', '/orders', OrderController::class, 'list', 'auth');
    $r->get('v1', '/orders/{orderId}', OrderController::class, 'detail', 'auth');
    $r->get('v1', '/orders/{orderId}/timeline', OrderController::class, 'timeline', 'auth');
    $r->get('v1', '/orders/{orderId}/invoice', OrderController::class, 'invoice', 'auth');
    $r->get('v1', '/orders/{orderId}/shipments', OrderController::class, 'shipments', 'auth');
    $r->post('v1', '/orders/{orderId}/cancel', OrderController::class, 'cancel', 'auth');
    $r->get('v1', '/shipments/{shipmentId}/tracking', OrderController::class, 'tracking', 'auth');
    $r->get('v1', '/support/categories', SupportController::class, 'categories');
    $r->get('v1', '/support/tickets', SupportController::class, 'list', 'auth');
    $r->post('v1', '/support/tickets', SupportController::class, 'create', 'auth');
    $r->get('v1', '/support/tickets/{ticketId}', SupportController::class, 'detail', 'auth');
    $r->post('v1', '/support/tickets/{ticketId}/messages', SupportController::class, 'message', 'auth');
    $r->post('v1', '/support/tickets/{ticketId}/close', SupportController::class, 'close', 'auth');
    $r->post('v1', '/support/uploads', SupportController::class, 'upload', 'auth');
    $r->get('v1', '/admin/orders', AdminOperationsController::class, 'orders', ['orders.read']);
    $r->post('v1', '/admin/orders/{orderId}/transitions', AdminOperationsController::class, 'transition', ['orders.update_status']);
    $r->post('v1', '/admin/orders/{orderId}/notes', AdminOperationsController::class, 'note', ['orders.read']);
    $r->post('v1', '/admin/orders/{orderId}/shipments', AdminOperationsController::class, 'createShipment', ['orders.update_status']);
    $r->post('v1', '/admin/shipments/{shipmentId}/dispatch', AdminOperationsController::class, 'dispatchShipment', ['orders.update_status']);
    $r->get('v1', '/admin/customers', AdminOperationsController::class, 'customers', ['customers.read_limited']);
    $r->get('v1', '/admin/payments', AdminOperationsController::class, 'payments', ['payments.read']);
    $r->get('v1', '/admin/reports/sales-summary', AdminOperationsController::class, 'salesSummary', ['reports.read']);
    $r->get('v1', '/admin/reports/inventory-risk', AdminOperationsController::class, 'inventoryRisk', ['reports.read']);
    $r->get('v1', '/admin/tickets', AdminOperationsController::class, 'tickets', ['tickets.respond']);
    $r->get('v1', '/admin/tickets/{ticketId}', AdminOperationsController::class, 'ticket', ['tickets.respond']);
    $r->post('v1', '/admin/tickets/{ticketId}/messages', AdminOperationsController::class, 'ticketMessage', ['tickets.respond']);
    $r->post('v1', '/admin/tickets/{ticketId}/assign', AdminOperationsController::class, 'assignTicket', ['tickets.respond']);
    $r->post('v1', '/admin/tickets/{ticketId}/status', AdminOperationsController::class, 'ticketStatus', ['tickets.respond']);
    $r->get('v1', '/admin/products', AdminCatalogController::class, 'products', ['catalog.read']);
    $r->post('v1', '/admin/products', AdminCatalogController::class, 'createProduct', ['catalog.write']);
    $r->patch('v1', '/admin/products/{productId}', AdminCatalogController::class, 'updateProduct', ['catalog.write']);
    $r->post('v1', '/admin/products/{productId}/publish', AdminCatalogController::class, 'publish', ['catalog.write']);
    $r->post('v1', '/admin/products/{productId}/archive', AdminCatalogController::class, 'archive', ['catalog.write']);
    $r->get('v1', '/admin/skus/{skuId}/pricing-tiers', AdminCatalogController::class, 'tiers', ['catalog.read']);
    $r->put('v1', '/admin/skus/{skuId}/pricing-tiers', AdminCatalogController::class, 'saveTiers', ['pricing.write']);
    $r->post('v1', '/admin/inventory/adjustments', AdminCatalogController::class, 'adjust', ['inventory.adjust']);
    $r->get('v1', '/admin/best-selling-products', AdminBestSellingController::class, 'index', ['catalog.read']);
    $r->post('v1', '/admin/best-selling-products', AdminBestSellingController::class, 'create', ['catalog.write']);
    $r->patch('v1', '/admin/best-selling-products/{itemId}', AdminBestSellingController::class, 'update', ['catalog.write']);
    $r->delete('v1', '/admin/best-selling-products/{itemId}', AdminBestSellingController::class, 'delete', ['catalog.write']);
    $r->get('v1', '/admin/coupons', AdminConfigurationController::class, 'coupons', ['catalog.write']);
    $r->post('v1', '/admin/coupons', AdminConfigurationController::class, 'createCoupon', ['catalog.write']);
    $r->patch('v1', '/admin/coupons/{couponId}', AdminConfigurationController::class, 'updateCoupon', ['catalog.write']);
    $r->get('v1', '/admin/settings/{setting}', AdminConfigurationController::class, 'setting', ['staff.manage']);
    $r->put('v1', '/admin/settings/{setting}', AdminConfigurationController::class, 'saveSetting', ['staff.manage']);
    $r->post('v1', '/admin/reports/exports', ReportController::class, 'create', ['reports.read']);
    $r->get('v1', '/admin/reports/exports/{jobId}', ReportController::class, 'status', ['reports.read']);
};
